/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations.index'
import { Route as AuthenticatedOrganizationsIdRouteImport } from './routes/_authenticated/organizations.$id'

const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/_authenticated/organizations/',
    path: '/organizations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrganizationsIdRoute =
  AuthenticatedOrganizationsIdRouteImport.update({
    id: '/_authenticated/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/news': typeof NewsRoute
  '/pipeline': typeof PipelineRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/': typeof PeopleIndexRoute
  '/organizations/$id': typeof AuthenticatedOrganizationsIdRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/news': typeof NewsRoute
  '/pipeline': typeof PipelineRoute
  '/people/$id': typeof PeopleIdRoute
  '/people': typeof PeopleIndexRoute
  '/organizations/$id': typeof AuthenticatedOrganizationsIdRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/news': typeof NewsRoute
  '/pipeline': typeof PipelineRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/': typeof PeopleIndexRoute
  '/_authenticated/organizations/$id': typeof AuthenticatedOrganizationsIdRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/news'
    | '/pipeline'
    | '/people/$id'
    | '/people/'
    | '/organizations/$id'
    | '/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/news'
    | '/pipeline'
    | '/people/$id'
    | '/people'
    | '/organizations/$id'
    | '/organizations'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/news'
    | '/pipeline'
    | '/people/$id'
    | '/people/'
    | '/_authenticated/organizations/$id'
    | '/_authenticated/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  NewsRoute: typeof NewsRoute
  PipelineRoute: typeof PipelineRoute
  PeopleIdRoute: typeof PeopleIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  AuthenticatedOrganizationsIdRoute: typeof AuthenticatedOrganizationsIdRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizations/$id': {
      id: '/_authenticated/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof AuthenticatedOrganizationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  NewsRoute: NewsRoute,
  PipelineRoute: PipelineRoute,
  PeopleIdRoute: PeopleIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  AuthenticatedOrganizationsIdRoute: AuthenticatedOrganizationsIdRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
